Project_One/urls.py
from django.contrib import admin
from django.urls import path, include
# from app_one import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_one/', include('app_one.urls')),
    path('app_two/', include('app_two.urls')),
    # path('', views.index, name="index"),
]

app_one/urls.py
from django.urls import path
from app_one import views

app_name = 'app_one'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('home', views.home_view, name='home'),
    path('user_login', views.user_login_view, name='user_login'),
    path('user_logout', views.user_logout_view, name='user_logout'),
    path('user_registration', views.user_registration_view, name='user_registration'),  # noqa E501
    # path('form_page', views.form_page_view, name='form_page'),
    path('access_records_page', views.records_page_view, name='access_records_page'),  # noqa E501
]

app_two/urls.py
from django.urls import path
from app_two import views

app_name = 'app_two'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('relative_url_templates', views.relative_url_templates_view, name='relative_url_templates'),  # noqa E501
]

app_one/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.PROTECT)

    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):

        return self.user.username


class Topic(models.Model):

    top_name = models.CharField(max_length=128, unique=True)

    def __str__(self):

        return self.top_name


class Webpage(models.Model):

    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    name = models.CharField(max_length=128, unique=True)
    url = models.CharField(max_length=128, unique=True)

    def __str__(self):

        return self.name


class AccessRecord(models.Model):

    webpage = models.ForeignKey(Webpage, on_delete=models.PROTECT)
    date = models.DateField()

    def __str__(self):

        return str(self.webpage) + " was accessed on " + str(self.date)

app_two/models.py
from django.db import models

# Create your models here.

app_one/forms.py
from django import forms
# from django.core import validators
from django.contrib.auth.models import User
from app_one.models import UserProfileInfo


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():

        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoFrom(forms.ModelForm):

    class Meta():

        model = UserProfileInfo
        fields = ('portfolio', 'picture')


# def check_name_for_z(value):
#
#     if value[0].lower() != 'z':
#
#         raise forms.ValidationError("Name needs to start with z")
#
#
# class TestForm(forms.Form):
#
#     name = forms.CharField(validators=[check_name_for_z])
#     email = forms.EmailField()
#     verify_email = forms.EmailField(label='Enter your Email again:')
#     text = forms.CharField(widget=forms.Textarea)
#     botcatcher = forms.CharField(required=False, widget=forms.HiddenInput)
#
#     def clean(self):
#
#         all_clean_data = super().clean()
#         email = all_clean_data.get('email')
#         vemail = all_clean_data.get('verify_email')
#
#         if email != vemail:
#             raise forms.ValidationError("Emails don't match")
#
#     def clean_botcatcher(self):
#
#         botcatcher = self.cleaned_data.get('botcatcher')
#         if len(botcatcher) > 0:
#             raise forms.ValidationError("BOT Detected")
#         return botcatcher

app_one/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from app_one.models import AccessRecord
from app_one.forms import UserForm, UserProfileInfoFrom

# Create your views here.


def index(request):

    return HttpResponse("Hello World")


def home_view(request):

    return render(request, 'app_one/home.html')


def user_login_view(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:

                login(request, user)

                return HttpResponseRedirect('home')

            else:

                return HttpResponse('<h1>Account Not Active!</h1>')

        else:

            print('Login attempt failed!!')
            print('Username: {u} and password: {p}'.format(
                u=username, p=password))

            return HttpResponse('<h1>Invalid Credentials!</h1>')

    else:

        return render(request, 'app_one/user_login.html', context={})


@login_required
def user_logout_view(request):

    logout(request)

    return HttpResponseRedirect('user_login')


def user_registration_view(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileInfoFrom(data=request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_profile = user_profile_form.save(commit=False)
            user_profile.user = user

            if 'picture' in request.FILES:

                user_profile.profile = request.FILES['picture']

            user_profile.save()

            registered = True

        else:

            print(user_form.errors, user_profile_form.errors)

    else:

        user_form = UserForm()
        user_profile_form = UserProfileInfoFrom()

    return render(request, 'app_one/user_registration.html',
                  context={'user_form': user_form, 'user_profile_form': user_profile_form, 'registered': registered})


@login_required
def records_page_view(request):

    acc_rec_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': acc_rec_list}

    return render(request, 'app_one/access_records_page.html', context=date_dict)  # noqa E501


# def form_page_view(request):
#
#     form = TestForm()
#
#     if request.method == 'POST':
#
#         form = TestForm(request.POST)
#
#         if form.is_valid():
#
#             print("Validation Successful")
#             print("Name: " + form.cleaned_data['name'])
#             print("Email: " + form.cleaned_data['email'])
#             print("Text: " + form.cleaned_data['text'])
#
#     return render(request, 'app_one/form_page.html', context={'form': form})

app_two/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.


def home_view(request):

    context_dict = {'text': 'hello world', 'number': 100}

    return render(request, 'app_two/home.html', context=context_dict)


@login_required
def relative_url_templates_view(request):

    return render(request, 'app_two/relative_url_templates.html')

templates/app_one/access_records_page.html
<!DOCTYPE html>
{% extends "app_one/base.html" %}
{% load static %}

{% block body_block %}

  <link rel="stylesheet" href="{% static "app_one/css/access_records_style.css" %}">


  <h1>Welcome to Django Level 2</h1>
  <h2>Here are your Access Records:</h2>

  <div>

    {% if access_records %}

      <table class="access_records">

        <thead>

          <th>Site Name</th>
          <th>Date Accessed</th>

        </thead>

        {% for acc in access_records %}

          <tr>

            <td>{{ acc.webpage }}</td>
            <td>{{ acc.date }}</td>

          </tr>

        {% endfor %}

      </table>

    {% else %}

      <p>NO ACCESS RECORDS FOUND!</p>

    {% endif %}

  </div>

  <img src="{% static "app_one/images/WN9wt8.jpg" %}" alt="image didn't show">

{% endblock %}

templates/app_one/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-static-top">
      <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'admin:index' %}">ADMIN</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">

            <li class="nav-item"><a class="nav-link" href="{% url 'app_one:home' %}">App One Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'app_two:home' %}">App Two Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'app_one:user_registration' %}">User Registration</a></li>

            {% if user.is_authenticated %}

              <li class="nav-item"><a class="nav-link" href="{% url 'app_one:access_records_page' %}">Access Records</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'app_two:relative_url_templates' %}">Relative URL</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'app_one:user_logout' %}">Logout</a></li>

            {% else %}

              <li class="nav-item"><a class="nav-link" href="{% url 'app_one:user_login' %}">User Login</a></li>

            {% endif %}

          </ul>
        </div>

      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

templates/app_one/form_page.html
<!DOCTYPE html>
{% extends "app_one/base.html" %}
{% block body_block %}

  <h1>Fill out the form!</h1>

  <div class="container">

    <form method="POST">

      {{ form.as_p }}
      {% csrf_token %}

      <button type="submit" class="btn btn-primary">Submit</button>

    </form>

  </div>

{% endblock %}

templates/app_one/home.html
<!DOCTYPE html>
{% extends "app_one/base.html" %}
{% block body_block %}

  <h1>Welcome to App One Home page!</h1>

{% endblock %}

templates/app_one/user_login.html
<!DOCTYPE html>
{% extends "app_one/base.html" %}
{% block body_block %}

  <div class="jumbotron">

    <h1>Welcome to the Login Page</h1>

    <form action="{% url 'app_one:user_login' %}" method="POST">

      {% csrf_token %}

      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="enter username here">

      <label for="password">Password:</label>
      <input type="password" name="password" placeholder="enter password here">

      <button type="submit" class="btn btn-primary">Login</button>

    </form>

    <p>If you are a new User please <a href="{% url 'app_one:user_registration' %}">Register</a> here</p>

  </div>

{% endblock %}

templates/app_one/user_registration.html
<!DOCTYPE html>
{% extends "app_one/base.html" %}
{% block body_block %}

  <div class="jumbotron">

    {% if registered %}

      <h1>Thank you for registering!</h1>

    {% else %}

      <h1>Welcome to User Registration page!</h1>
      <h3>Fill out the form below:</h3>

      <form enctype="multipart/form-data" method="POST">

        {% csrf_token %}
        {{ user_form.as_p }}
        {{ user_profile_form.as_p }}

        <button type="submit" class="btn btn-primary">Register</button>

      </form>

    {% endif %}

  </div>

{% endblock %}

templates/app_two/home.html
<!DOCTYPE html>
{% extends "app_one/base.html" %}
{% block body_block %}
{% load filters %}

  <h1>Welcome to App Two Home Page!</h1>

  <p>{{ text | remove_all_char:'l' }}</p>

  <p>{{ number | add:10 }}</p>

{% endblock %}

templates/app_two/relative_url_templates.html
<!DOCTYPE html>
{% extends "app_one/base.html" %}
{% block body_block %}

  <h1>Welcome to Relative URL Templates</h1>
  <p>Redirect to <a href="{% url 'admin:index' %}">Admin Index</a> Page</p>
  <p>Redirect to <a href="{% url 'app_one:home' %}">App One Home</a> Page</p>
  <p>Redirect to <a href="{% url 'app_two:home' %}">App Two Home</a> Page</p>

{% endblock %}